GCC = /root/buildroot-precompiled-2017.08/output/host/usr/bin/arm-linux-gcc
COPTS = -Wall
CLIENT = blink
BIN = blink


all:

	$(GCC)  $(COPTS) $(CLIENT).c -o $(BIN) 

clean:
	rm -f $(BIN)

# usr/local/lib
